supportedActions:
  null: ["search"]
  search: ["on_search"]
  on_search: ["search", "select", "confirm"]
  select: ["on_select"]
  on_select: ["init"]
  init: ["on_init"]
  on_init: ["init", "confirm"]
  confirm: ["on_confirm"]

apiProperties:
  search:
    async_predecessor: null
    transaction_partner: []
  on_search:
    async_predecessor: "search"
    transaction_partner: ["search"]
  select:
    async_predecessor: null
    transaction_partner: ["search"]
  on_select:
    async_predecessor: "select"
    transaction_partner: ["select", "search", "on_search"]
  init:
    async_predecessor: null
    transaction_partner: ["select", "search", "on_search", "on_select"]
  on_init:
    async_predecessor: "init"
    transaction_partner: ["init", "select", "search", "on_search", "on_select"]
  confirm:
    async_predecessor: null
    transaction_partner: ["search", "on_search"]
  on_confirm:
    async_predecessor: "confirm"
    transaction_partner: ["confirm"]  # Only require confirm as transaction partner
